version: "3.9"
services:
  app:
    build: . 
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blog # Khởi tạo database
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: 123
      DATABASE_URL: postgresql://$blog:123@db:5432/blog
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
