[pytest] # Cấu hình dành cho pytest
pythonpath = . # Thêm thư mục gốc project vào pythonpath
testpaths = tests # khi chạy pytest, vào thư mục tests/ tìm test
python_files = test_*.py # Các file test
python_classes = Test* # Class test
python_functions = test_* # Hàm test
addopts = -v --tb=short # Hiển thị kết quả