# Cấu hình dành cho pytest
[pytest] 

# Thêm thư mục gốc project vào pythonpath
pythonpath = .  

# khi chạy pytest, vào thư mục tests/ tìm test
testpaths = tests 

# Các file test
python_files = test_*.py 

# Class test
python_classes = Test* 

# Hàm test
python_functions = test_* 

# Hiển thị tên test và traceback 
addopts = -v --tb=short 