name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/my-blog
  # Github secret
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }} 
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Tải source code của repo xuống runner

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run pytest
        run: pytest tests/ -v

  test-docker-compose:
    needs: test-python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start compose
        run: docker compose -f docker-compose.test.yaml up -d

      - name: Wait
        run: sleep 15

      - name: Migrate database
        run: docker compose -f docker-compose.test.yaml exec app flask db upgrade

      - name: Smoke test
        run: curl http://localhost:5000
      
      - name: Show compose logs if failed
        if: failure()
        run: docker compose -f docker-compose.test.yaml logs

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.test.yaml down
  build-and-push:
    needs: test-docker-compose
    # Chạy khi workflow chạy trên branch main
    # Nếu không thỏa mãn if -> skip chứ không báo lỗi
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    # Cấp quyền cho Github Token
    permissions:
      contents: read # được phép đọc source code của repo
      packages: write # được phép push Docker image lên GHCR

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3 # docker login ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Tên tài khoản Github
          password: ${{ secrets.GITHUB_TOKEN }} # token Github tự sinh ra cho workflow

      - name: Build and Push Image
        uses: docker/build-push-action@v5 # docker build, push
        with:
          context: . # build từ thư mục hiện tại
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest 
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          # latest: con trò đến phiên bản mới nhất
          # sha: Tag cố định không bao giờ thay đổi
    deploy:
      needs: build-and-push
      if: github.ref == 'refs/heads/main'

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Install Ansible
          run: |
            sudo apt update
            sudo apt install -y ansible

        - name: Setup SSH Key
          run: |
            mkdir -p ~/.ssh/aws
            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/aws/my-blog-key.pem
            chmod 600 ~/.ssh/aws/my-blog-key.pem
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
           # 600: Set quyền file 600 để SSH mới hoạt động
           # ssh-keyscan -H: lấy public host key của server rồi thêm vào known_hosts

      - name: Create Ansible Vault password file
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.txt

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/deploy.yaml \
            -i ansible/inventory.ini \
            --vault-password-file vault_pass.txt
        # Nhập ansible vault pass 

      - name: Wait for application
        run: sleep 10

      - name: Health Check
        run: |
          curl -f https://son-blog.duckdns.org